require 'inside_sales/soap/default'
require 'inside_sales/soap/defaultMappingRegistry'
require 'soap/rpc/driver'

module InsideSales::SOAP

class Client < ::SOAP::RPC::Driver
  DefaultEndpointUrl = "https://recruitmilitary.insidesales.com/do=noauth/soap/service/AllInsideSalesServices"
  NsWwwInsidesalesCom = "http://www.insidesales.com/"

  Methods = [
    [ XSD::QName.new(NsWwwInsidesalesCom, "login"),
      "https://recruitmilitary.insidesales.com/do=noauth/soap/service/AllInsideSalesServices",
      "login",
      [ ["in", "username", ["::SOAP::SOAPString"]],
        ["in", "password", ["::SOAP::SOAPString"]],
        ["retval", "return", ["::SOAP::SOAPBoolean"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsWwwInsidesalesCom, "__call"),
      "https://recruitmilitary.insidesales.com/do=noauth/soap/service/AllInsideSalesServices",
      "m___call",
      [],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsWwwInsidesalesCom, "addTask"),
      "https://recruitmilitary.insidesales.com/do=noauth/soap/service/AllInsideSalesServices",
      "addTask",
      [ ["in", "task", ["InsideSales::SOAP::Task", "http://www.insidesales.com/", "Task"]],
        ["retval", "return", ["::SOAP::SOAPInt"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsWwwInsidesalesCom, "updateTasks"),
      "https://recruitmilitary.insidesales.com/do=noauth/soap/service/AllInsideSalesServices",
      "updateTasks",
      [ ["in", "tasks", ["InsideSales::SOAP::ArrayOfTask", "http://www.insidesales.com/", "ArrayOfTask"]],
        ["retval", "return", ["InsideSales::SOAP::ArrayOfint", "http://www.insidesales.com/", "ArrayOfint"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsWwwInsidesalesCom, "updateTask"),
      "https://recruitmilitary.insidesales.com/do=noauth/soap/service/AllInsideSalesServices",
      "updateTask",
      [ ["in", "task", ["InsideSales::SOAP::Task", "http://www.insidesales.com/", "Task"]],
        ["retval", "return", ["::SOAP::SOAPInt"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsWwwInsidesalesCom, "deleteTasks"),
      "https://recruitmilitary.insidesales.com/do=noauth/soap/service/AllInsideSalesServices",
      "deleteTasks",
      [ ["in", "task_ids", ["InsideSales::SOAP::ArrayOfint", "http://www.insidesales.com/", "ArrayOfint"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsWwwInsidesalesCom, "deleteTask"),
      "https://recruitmilitary.insidesales.com/do=noauth/soap/service/AllInsideSalesServices",
      "deleteTask",
      [ ["in", "task_id", ["::SOAP::SOAPInt"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsWwwInsidesalesCom, "getTasks"),
      "https://recruitmilitary.insidesales.com/do=noauth/soap/service/AllInsideSalesServices",
      "getTasks",
      [ ["in", "filters", ["InsideSales::SOAP::ArrayOfFilter", "http://www.insidesales.com/", "ArrayOfFilter"]],
        ["retval", "return", ["InsideSales::SOAP::ArrayOfTask", "http://www.insidesales.com/", "ArrayOfTask"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsWwwInsidesalesCom, "getSkillOptions"),
      "https://recruitmilitary.insidesales.com/do=noauth/soap/service/AllInsideSalesServices",
      "getSkillOptions",
      [ ["in", "skill_id", ["::SOAP::SOAPInt"]],
        ["retval", "return", ["InsideSales::SOAP::ArrayOfSkillOption", "http://www.insidesales.com/", "ArrayOfSkillOption"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsWwwInsidesalesCom, "getRoutingRules"),
      "https://recruitmilitary.insidesales.com/do=noauth/soap/service/AllInsideSalesServices",
      "getRoutingRules",
      [ ["retval", "return", ["InsideSales::SOAP::ArrayOfRoutingRule", "http://www.insidesales.com/", "ArrayOfRoutingRule"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsWwwInsidesalesCom, "getQuotas"),
      "https://recruitmilitary.insidesales.com/do=noauth/soap/service/AllInsideSalesServices",
      "getQuotas",
      [ ["in", "rule_id", ["::SOAP::SOAPInt"]],
        ["retval", "return", ["InsideSales::SOAP::ArrayOfQuota", "http://www.insidesales.com/", "ArrayOfQuota"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsWwwInsidesalesCom, "getSkills"),
      "https://recruitmilitary.insidesales.com/do=noauth/soap/service/AllInsideSalesServices",
      "getSkills",
      [ ["in", "routing_rule_id", ["::SOAP::SOAPInt"]],
        ["retval", "return", ["InsideSales::SOAP::ArrayOfSkill", "http://www.insidesales.com/", "ArrayOfSkill"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsWwwInsidesalesCom, "getSkillOptionEmployees"),
      "https://recruitmilitary.insidesales.com/do=noauth/soap/service/AllInsideSalesServices",
      "getSkillOptionEmployees",
      [ ["in", "skill_id", ["::SOAP::SOAPInt"]],
        ["in", "option_id", ["::SOAP::SOAPInt"]],
        ["retval", "return", ["InsideSales::SOAP::ArrayOfSkillOptionEmployee", "http://www.insidesales.com/", "ArrayOfSkillOptionEmployee"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsWwwInsidesalesCom, "addUpdateRoutingRule"),
      "https://recruitmilitary.insidesales.com/do=noauth/soap/service/AllInsideSalesServices",
      "addUpdateRoutingRule",
      [ ["in", "routing_rule", ["InsideSales::SOAP::RoutingRule", "http://www.insidesales.com/", "RoutingRule"]],
        ["retval", "return", ["::SOAP::SOAPInt"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsWwwInsidesalesCom, "deleteRoutingRule"),
      "https://recruitmilitary.insidesales.com/do=noauth/soap/service/AllInsideSalesServices",
      "deleteRoutingRule",
      [ ["in", "rule_id", ["::SOAP::SOAPInt"]],
        ["retval", "return", ["::SOAP::SOAPBoolean"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsWwwInsidesalesCom, "addUpdateQuota"),
      "https://recruitmilitary.insidesales.com/do=noauth/soap/service/AllInsideSalesServices",
      "addUpdateQuota",
      [ ["in", "routing_rule", ["InsideSales::SOAP::Quota", "http://www.insidesales.com/", "Quota"]],
        ["retval", "return", ["::SOAP::SOAPBoolean"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsWwwInsidesalesCom, "deleteQuota"),
      "https://recruitmilitary.insidesales.com/do=noauth/soap/service/AllInsideSalesServices",
      "deleteQuota",
      [ ["in", "routing_rule_id", ["::SOAP::SOAPInt"]],
        ["in", "employee_id", ["::SOAP::SOAPInt"]],
        ["retval", "return", ["::SOAP::SOAPBoolean"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsWwwInsidesalesCom, "addUpdateSkillOptionEmployee"),
      "https://recruitmilitary.insidesales.com/do=noauth/soap/service/AllInsideSalesServices",
      "addUpdateSkillOptionEmployee",
      [ ["in", "skill_id", ["::SOAP::SOAPInt"]],
        ["in", "option_id", ["::SOAP::SOAPInt"]],
        ["in", "employee_id", ["::SOAP::SOAPInt"]],
        ["in", "proficiency", ["::SOAP::SOAPInt"]],
        ["retval", "return", ["::SOAP::SOAPBoolean"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsWwwInsidesalesCom, "deleteSkillOptionEmployee"),
      "https://recruitmilitary.insidesales.com/do=noauth/soap/service/AllInsideSalesServices",
      "deleteSkillOptionEmployee",
      [ ["in", "skill_id", ["::SOAP::SOAPInt"]],
        ["in", "option_id", ["::SOAP::SOAPInt"]],
        ["in", "employee_id", ["::SOAP::SOAPInt"]],
        ["retval", "return", ["::SOAP::SOAPBoolean"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsWwwInsidesalesCom, "setSkillOptionCampaign"),
      "https://recruitmilitary.insidesales.com/do=noauth/soap/service/AllInsideSalesServices",
      "setSkillOptionCampaign",
      [ ["in", "skill_id", ["::SOAP::SOAPInt"]],
        ["in", "option_id", ["::SOAP::SOAPInt"]],
        ["in", "campaign_id", ["::SOAP::SOAPInt"]],
        ["retval", "return", ["::SOAP::SOAPBoolean"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsWwwInsidesalesCom, "addNote"),
      "https://recruitmilitary.insidesales.com/do=noauth/soap/service/AllInsideSalesServices",
      "addNote",
      [ ["in", "note", ["InsideSales::SOAP::Note", "http://www.insidesales.com/", "Note"]],
        ["retval", "return", ["::SOAP::SOAPInt"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsWwwInsidesalesCom, "updateNotes"),
      "https://recruitmilitary.insidesales.com/do=noauth/soap/service/AllInsideSalesServices",
      "updateNotes",
      [ ["in", "notes", ["InsideSales::SOAP::ArrayOfNote", "http://www.insidesales.com/", "ArrayOfNote"]],
        ["retval", "return", ["InsideSales::SOAP::ArrayOfint", "http://www.insidesales.com/", "ArrayOfint"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsWwwInsidesalesCom, "updateNote"),
      "https://recruitmilitary.insidesales.com/do=noauth/soap/service/AllInsideSalesServices",
      "updateNote",
      [ ["in", "note", ["InsideSales::SOAP::Note", "http://www.insidesales.com/", "Note"]],
        ["retval", "return", ["::SOAP::SOAPInt"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsWwwInsidesalesCom, "deleteNotes"),
      "https://recruitmilitary.insidesales.com/do=noauth/soap/service/AllInsideSalesServices",
      "deleteNotes",
      [ ["in", "note_ids", ["InsideSales::SOAP::ArrayOfint", "http://www.insidesales.com/", "ArrayOfint"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsWwwInsidesalesCom, "deleteNote"),
      "https://recruitmilitary.insidesales.com/do=noauth/soap/service/AllInsideSalesServices",
      "deleteNote",
      [ ["in", "note_id", ["::SOAP::SOAPInt"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsWwwInsidesalesCom, "getNotes"),
      "https://recruitmilitary.insidesales.com/do=noauth/soap/service/AllInsideSalesServices",
      "getNotes",
      [ ["in", "filters", ["InsideSales::SOAP::ArrayOfFilter", "http://www.insidesales.com/", "ArrayOfFilter"]],
        ["retval", "return", ["InsideSales::SOAP::ArrayOfNote", "http://www.insidesales.com/", "ArrayOfNote"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsWwwInsidesalesCom, "RouteLead"),
      "https://recruitmilitary.insidesales.com/do=noauth/soap/service/AllInsideSalesServices",
      "routeLead",
      [ ["in", "lead_id", ["::SOAP::SOAPInt"]],
        ["in", "routing_rule_id", ["::SOAP::SOAPInt"]],
        ["retval", "return", ["::SOAP::SOAPBoolean"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsWwwInsidesalesCom, "updateLead"),
      "https://recruitmilitary.insidesales.com/do=noauth/soap/service/AllInsideSalesServices",
      "updateLead",
      [ ["in", "lead", ["InsideSales::SOAP::Lead", "http://www.insidesales.com/", "Lead"]],
        ["retval", "return", ["::SOAP::SOAPInt"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsWwwInsidesalesCom, "updateLeads"),
      "https://recruitmilitary.insidesales.com/do=noauth/soap/service/AllInsideSalesServices",
      "updateLeads",
      [ ["in", "leads", ["InsideSales::SOAP::ArrayOfLead", "http://www.insidesales.com/", "ArrayOfLead"]],
        ["retval", "return", ["InsideSales::SOAP::ArrayOfint", "http://www.insidesales.com/", "ArrayOfint"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsWwwInsidesalesCom, "deleteLead"),
      "https://recruitmilitary.insidesales.com/do=noauth/soap/service/AllInsideSalesServices",
      "deleteLead",
      [ ["in", "lead_id", ["::SOAP::SOAPInt"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsWwwInsidesalesCom, "deleteLeads"),
      "https://recruitmilitary.insidesales.com/do=noauth/soap/service/AllInsideSalesServices",
      "deleteLeads",
      [ ["in", "lead_ids", ["InsideSales::SOAP::ArrayOfint", "http://www.insidesales.com/", "ArrayOfint"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsWwwInsidesalesCom, "addLead"),
      "https://recruitmilitary.insidesales.com/do=noauth/soap/service/AllInsideSalesServices",
      "addLead",
      [ ["in", "lead", ["InsideSales::SOAP::Lead", "http://www.insidesales.com/", "Lead"]],
        ["retval", "return", ["::SOAP::SOAPInt"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsWwwInsidesalesCom, "convertLead"),
      "https://recruitmilitary.insidesales.com/do=noauth/soap/service/AllInsideSalesServices",
      "convertLead",
      [ ["in", "id", ["::SOAP::SOAPInt"]],
        ["retval", "return", ["::SOAP::SOAPInt"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsWwwInsidesalesCom, "getLeads"),
      "https://recruitmilitary.insidesales.com/do=noauth/soap/service/AllInsideSalesServices",
      "getLeads",
      [ ["in", "filters", ["InsideSales::SOAP::ArrayOfFilter", "http://www.insidesales.com/", "ArrayOfFilter"]],
        ["retval", "return", ["InsideSales::SOAP::ArrayOfLead", "http://www.insidesales.com/", "ArrayOfLead"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsWwwInsidesalesCom, "addEventAttendee"),
      "https://recruitmilitary.insidesales.com/do=noauth/soap/service/AllInsideSalesServices",
      "addEventAttendee",
      [ ["in", "event_id", ["::SOAP::SOAPInt"]],
        ["in", "attendee_type", ["::SOAP::SOAPString"]],
        ["in", "id", ["::SOAP::SOAPInt"]],
        ["in", "extra_data", ["::SOAP::SOAPString"]],
        ["retval", "return", ["::SOAP::SOAPBoolean"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsWwwInsidesalesCom, "addEventContactAttendee"),
      "https://recruitmilitary.insidesales.com/do=noauth/soap/service/AllInsideSalesServices",
      "addEventContactAttendee",
      [ ["in", "event_id", ["::SOAP::SOAPInt"]],
        ["in", "contact_user_id", ["::SOAP::SOAPInt"]],
        ["in", "extra_data", ["::SOAP::SOAPString"]],
        ["retval", "return", ["::SOAP::SOAPBoolean"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsWwwInsidesalesCom, "addEventEmployeeAttendee"),
      "https://recruitmilitary.insidesales.com/do=noauth/soap/service/AllInsideSalesServices",
      "addEventEmployeeAttendee",
      [ ["in", "event_id", ["::SOAP::SOAPInt"]],
        ["in", "employee_user_id", ["::SOAP::SOAPInt"]],
        ["in", "extra_data", ["::SOAP::SOAPString"]],
        ["retval", "return", ["::SOAP::SOAPBoolean"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsWwwInsidesalesCom, "addEventLeadAttendee"),
      "https://recruitmilitary.insidesales.com/do=noauth/soap/service/AllInsideSalesServices",
      "addEventLeadAttendee",
      [ ["in", "event_id", ["::SOAP::SOAPInt"]],
        ["in", "contact_info_id", ["::SOAP::SOAPInt"]],
        ["in", "extra_data", ["::SOAP::SOAPString"]],
        ["retval", "return", ["::SOAP::SOAPBoolean"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsWwwInsidesalesCom, "addEvent"),
      "https://recruitmilitary.insidesales.com/do=noauth/soap/service/AllInsideSalesServices",
      "addEvent",
      [ ["in", "event", ["InsideSales::SOAP::Event", "http://www.insidesales.com/", "Event"]],
        ["retval", "return", ["::SOAP::SOAPInt"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsWwwInsidesalesCom, "updateEvent"),
      "https://recruitmilitary.insidesales.com/do=noauth/soap/service/AllInsideSalesServices",
      "updateEvent",
      [ ["in", "event", ["InsideSales::SOAP::Event", "http://www.insidesales.com/", "Event"]],
        ["retval", "return", ["::SOAP::SOAPInt"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsWwwInsidesalesCom, "updateEvents"),
      "https://recruitmilitary.insidesales.com/do=noauth/soap/service/AllInsideSalesServices",
      "updateEvents",
      [ ["in", "events", ["InsideSales::SOAP::ArrayOfEvent", "http://www.insidesales.com/", "ArrayOfEvent"]],
        ["retval", "return", ["InsideSales::SOAP::ArrayOfInt", "http://www.insidesales.com/", "ArrayOfInt"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsWwwInsidesalesCom, "deleteEvents"),
      "https://recruitmilitary.insidesales.com/do=noauth/soap/service/AllInsideSalesServices",
      "deleteEvents",
      [ ["in", "event_ids", ["InsideSales::SOAP::ArrayOfint", "http://www.insidesales.com/", "ArrayOfint"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsWwwInsidesalesCom, "deleteEvent"),
      "https://recruitmilitary.insidesales.com/do=noauth/soap/service/AllInsideSalesServices",
      "deleteEvent",
      [ ["in", "event_id", ["::SOAP::SOAPInt"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsWwwInsidesalesCom, "getEvents"),
      "https://recruitmilitary.insidesales.com/do=noauth/soap/service/AllInsideSalesServices",
      "getEvents",
      [ ["in", "filter", ["InsideSales::SOAP::ArrayOfFilter", "http://www.insidesales.com/", "ArrayOfFilter"]],
        ["retval", "return", ["InsideSales::SOAP::ArrayOfEvent", "http://www.insidesales.com/", "ArrayOfEvent"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsWwwInsidesalesCom, "getEventLeadAttendees"),
      "https://recruitmilitary.insidesales.com/do=noauth/soap/service/AllInsideSalesServices",
      "getEventLeadAttendees",
      [ ["in", "event_id", ["::SOAP::SOAPInt"]],
        ["retval", "return", ["InsideSales::SOAP::ArrayOfEventAttendee", "http://www.insidesales.com/", "ArrayOfEventAttendee"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsWwwInsidesalesCom, "getEventContactAttendees"),
      "https://recruitmilitary.insidesales.com/do=noauth/soap/service/AllInsideSalesServices",
      "getEventContactAttendees",
      [ ["in", "event_id", ["::SOAP::SOAPInt"]],
        ["retval", "return", ["InsideSales::SOAP::ArrayOfEventAttendee", "http://www.insidesales.com/", "ArrayOfEventAttendee"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsWwwInsidesalesCom, "getEventEmployeeAttendees"),
      "https://recruitmilitary.insidesales.com/do=noauth/soap/service/AllInsideSalesServices",
      "getEventEmployeeAttendees",
      [ ["in", "event_id", ["::SOAP::SOAPInt"]],
        ["retval", "return", ["InsideSales::SOAP::ArrayOfEventAttendee", "http://www.insidesales.com/", "ArrayOfEventAttendee"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsWwwInsidesalesCom, "addEmployee"),
      "https://recruitmilitary.insidesales.com/do=noauth/soap/service/AllInsideSalesServices",
      "addEmployee",
      [ ["in", "employee", ["InsideSales::SOAP::Employee", "http://www.insidesales.com/", "Employee"]],
        ["retval", "return", ["::SOAP::SOAPInt"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsWwwInsidesalesCom, "updateEmployees"),
      "https://recruitmilitary.insidesales.com/do=noauth/soap/service/AllInsideSalesServices",
      "updateEmployees",
      [ ["in", "employees", ["InsideSales::SOAP::ArrayOfEmployee", "http://www.insidesales.com/", "ArrayOfEmployee"]],
        ["retval", "return", ["InsideSales::SOAP::ArrayOfint", "http://www.insidesales.com/", "ArrayOfint"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsWwwInsidesalesCom, "updateEmployee"),
      "https://recruitmilitary.insidesales.com/do=noauth/soap/service/AllInsideSalesServices",
      "updateEmployee",
      [ ["in", "employee", ["InsideSales::SOAP::Employee", "http://www.insidesales.com/", "Employee"]],
        ["retval", "return", ["::SOAP::SOAPInt"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsWwwInsidesalesCom, "deleteEmployees"),
      "https://recruitmilitary.insidesales.com/do=noauth/soap/service/AllInsideSalesServices",
      "deleteEmployees",
      [ ["in", "employee_ids", ["InsideSales::SOAP::ArrayOfint", "http://www.insidesales.com/", "ArrayOfint"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsWwwInsidesalesCom, "deleteEmployee"),
      "https://recruitmilitary.insidesales.com/do=noauth/soap/service/AllInsideSalesServices",
      "deleteEmployee",
      [ ["in", "employee_id", ["::SOAP::SOAPInt"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsWwwInsidesalesCom, "checkAvailableLicenses"),
      "https://recruitmilitary.insidesales.com/do=noauth/soap/service/AllInsideSalesServices",
      "checkAvailableLicenses",
      [ ["in", "license", ["::SOAP::SOAPString"]],
        ["retval", "return", ["InsideSales::SOAP::ArrayOfstring", "http://www.insidesales.com/", "ArrayOfstring"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsWwwInsidesalesCom, "getEmployees"),
      "https://recruitmilitary.insidesales.com/do=noauth/soap/service/AllInsideSalesServices",
      "getEmployees",
      [ ["in", "filters", ["InsideSales::SOAP::ArrayOfFilter", "http://www.insidesales.com/", "ArrayOfFilter"]],
        ["retval", "return", ["InsideSales::SOAP::ArrayOfEmployee", "http://www.insidesales.com/", "ArrayOfEmployee"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsWwwInsidesalesCom, "addDeal"),
      "https://recruitmilitary.insidesales.com/do=noauth/soap/service/AllInsideSalesServices",
      "addDeal",
      [ ["in", "deal", ["InsideSales::SOAP::Deal", "http://www.insidesales.com/", "Deal"]],
        ["retval", "return", ["::SOAP::SOAPInt"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsWwwInsidesalesCom, "updateDeals"),
      "https://recruitmilitary.insidesales.com/do=noauth/soap/service/AllInsideSalesServices",
      "updateDeals",
      [ ["in", "deals", ["InsideSales::SOAP::ArrayOfDeal", "http://www.insidesales.com/", "ArrayOfDeal"]],
        ["retval", "return", ["InsideSales::SOAP::ArrayOfint", "http://www.insidesales.com/", "ArrayOfint"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsWwwInsidesalesCom, "updateDeal"),
      "https://recruitmilitary.insidesales.com/do=noauth/soap/service/AllInsideSalesServices",
      "updateDeal",
      [ ["in", "deal", ["InsideSales::SOAP::Deal", "http://www.insidesales.com/", "Deal"]],
        ["retval", "return", ["::SOAP::SOAPInt"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsWwwInsidesalesCom, "deleteDeals"),
      "https://recruitmilitary.insidesales.com/do=noauth/soap/service/AllInsideSalesServices",
      "deleteDeals",
      [ ["in", "deal_ids", ["InsideSales::SOAP::ArrayOfint", "http://www.insidesales.com/", "ArrayOfint"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsWwwInsidesalesCom, "deleteDeal"),
      "https://recruitmilitary.insidesales.com/do=noauth/soap/service/AllInsideSalesServices",
      "deleteDeal",
      [ ["in", "deal_id", ["::SOAP::SOAPInt"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsWwwInsidesalesCom, "getDeals"),
      "https://recruitmilitary.insidesales.com/do=noauth/soap/service/AllInsideSalesServices",
      "getDeals",
      [ ["in", "filters", ["InsideSales::SOAP::ArrayOfFilter", "http://www.insidesales.com/", "ArrayOfFilter"]],
        ["retval", "return", ["InsideSales::SOAP::ArrayOfDeal", "http://www.insidesales.com/", "ArrayOfDeal"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsWwwInsidesalesCom, "addContact"),
      "https://recruitmilitary.insidesales.com/do=noauth/soap/service/AllInsideSalesServices",
      "addContact",
      [ ["in", "contact", ["InsideSales::SOAP::Contact", "http://www.insidesales.com/", "Contact"]],
        ["retval", "return", ["::SOAP::SOAPInt"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsWwwInsidesalesCom, "updateContacts"),
      "https://recruitmilitary.insidesales.com/do=noauth/soap/service/AllInsideSalesServices",
      "updateContacts",
      [ ["in", "contacts", ["InsideSales::SOAP::ArrayOfContact", "http://www.insidesales.com/", "ArrayOfContact"]],
        ["retval", "return", ["InsideSales::SOAP::ArrayOfint", "http://www.insidesales.com/", "ArrayOfint"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsWwwInsidesalesCom, "updateContact"),
      "https://recruitmilitary.insidesales.com/do=noauth/soap/service/AllInsideSalesServices",
      "updateContact",
      [ ["in", "contact", ["InsideSales::SOAP::Contact", "http://www.insidesales.com/", "Contact"]],
        ["retval", "return", ["::SOAP::SOAPInt"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsWwwInsidesalesCom, "deleteContacts"),
      "https://recruitmilitary.insidesales.com/do=noauth/soap/service/AllInsideSalesServices",
      "deleteContacts",
      [ ["in", "contact_ids", ["InsideSales::SOAP::ArrayOfint", "http://www.insidesales.com/", "ArrayOfint"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsWwwInsidesalesCom, "deleteContact"),
      "https://recruitmilitary.insidesales.com/do=noauth/soap/service/AllInsideSalesServices",
      "deleteContact",
      [ ["in", "contact_id", ["::SOAP::SOAPInt"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsWwwInsidesalesCom, "getContacts"),
      "https://recruitmilitary.insidesales.com/do=noauth/soap/service/AllInsideSalesServices",
      "getContacts",
      [ ["in", "filters", ["InsideSales::SOAP::ArrayOfFilter", "http://www.insidesales.com/", "ArrayOfFilter"]],
        ["retval", "return", ["InsideSales::SOAP::ArrayOfContact", "http://www.insidesales.com/", "ArrayOfContact"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsWwwInsidesalesCom, "addCase"),
      "https://recruitmilitary.insidesales.com/do=noauth/soap/service/AllInsideSalesServices",
      "addCase",
      [ ["in", "case", ["InsideSales::SOAP::Kase", "http://www.insidesales.com/", "Kase"]],
        ["retval", "return", ["::SOAP::SOAPInt"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsWwwInsidesalesCom, "updateCases"),
      "https://recruitmilitary.insidesales.com/do=noauth/soap/service/AllInsideSalesServices",
      "updateCases",
      [ ["in", "cases", ["InsideSales::SOAP::ArrayOfKase", "http://www.insidesales.com/", "ArrayOfKase"]],
        ["retval", "return", ["InsideSales::SOAP::ArrayOfint", "http://www.insidesales.com/", "ArrayOfint"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsWwwInsidesalesCom, "updateCase"),
      "https://recruitmilitary.insidesales.com/do=noauth/soap/service/AllInsideSalesServices",
      "updateCase",
      [ ["in", "case", ["InsideSales::SOAP::Kase", "http://www.insidesales.com/", "Kase"]],
        ["retval", "return", ["::SOAP::SOAPInt"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsWwwInsidesalesCom, "deleteCases"),
      "https://recruitmilitary.insidesales.com/do=noauth/soap/service/AllInsideSalesServices",
      "deleteCases",
      [ ["in", "case_ids", ["InsideSales::SOAP::ArrayOfint", "http://www.insidesales.com/", "ArrayOfint"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsWwwInsidesalesCom, "deleteCase"),
      "https://recruitmilitary.insidesales.com/do=noauth/soap/service/AllInsideSalesServices",
      "deleteCase",
      [ ["in", "case_id", ["::SOAP::SOAPInt"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsWwwInsidesalesCom, "getCases"),
      "https://recruitmilitary.insidesales.com/do=noauth/soap/service/AllInsideSalesServices",
      "getCases",
      [ ["in", "filters", ["InsideSales::SOAP::ArrayOfFilter", "http://www.insidesales.com/", "ArrayOfFilter"]],
        ["retval", "return", ["InsideSales::SOAP::ArrayOfKase", "http://www.insidesales.com/", "ArrayOfKase"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsWwwInsidesalesCom, "addAccount"),
      "https://recruitmilitary.insidesales.com/do=noauth/soap/service/AllInsideSalesServices",
      "addAccount",
      [ ["in", "account", ["InsideSales::SOAP::Account", "http://www.insidesales.com/", "Account"]],
        ["retval", "return", ["::SOAP::SOAPInt"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsWwwInsidesalesCom, "updateAccounts"),
      "https://recruitmilitary.insidesales.com/do=noauth/soap/service/AllInsideSalesServices",
      "updateAccounts",
      [ ["in", "accounts", ["InsideSales::SOAP::ArrayOfAccount", "http://www.insidesales.com/", "ArrayOfAccount"]],
        ["retval", "return", ["InsideSales::SOAP::ArrayOfint", "http://www.insidesales.com/", "ArrayOfint"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsWwwInsidesalesCom, "updateAccount"),
      "https://recruitmilitary.insidesales.com/do=noauth/soap/service/AllInsideSalesServices",
      "updateAccount",
      [ ["in", "account", ["InsideSales::SOAP::Account", "http://www.insidesales.com/", "Account"]],
        ["retval", "return", ["::SOAP::SOAPInt"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsWwwInsidesalesCom, "deleteAccounts"),
      "https://recruitmilitary.insidesales.com/do=noauth/soap/service/AllInsideSalesServices",
      "deleteAccounts",
      [ ["in", "account_ids", ["InsideSales::SOAP::ArrayOfint", "http://www.insidesales.com/", "ArrayOfint"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsWwwInsidesalesCom, "deleteAccount"),
      "https://recruitmilitary.insidesales.com/do=noauth/soap/service/AllInsideSalesServices",
      "deleteAccount",
      [ ["in", "account_id", ["::SOAP::SOAPInt"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsWwwInsidesalesCom, "getAccounts"),
      "https://recruitmilitary.insidesales.com/do=noauth/soap/service/AllInsideSalesServices",
      "getAccounts",
      [ ["in", "filters", ["InsideSales::SOAP::ArrayOfFilter", "http://www.insidesales.com/", "ArrayOfFilter"]],
        ["retval", "return", ["InsideSales::SOAP::ArrayOfAccount", "http://www.insidesales.com/", "ArrayOfAccount"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsWwwInsidesalesCom, "_addContactInfo"),
      "https://recruitmilitary.insidesales.com/do=noauth/soap/service/AllInsideSalesServices",
      "m__addContactInfo",
      [ ["in", "email", ["::SOAP::SOAPString"]],
        ["in", "phone", ["::SOAP::SOAPString"]],
        ["in", "fax", ["::SOAP::SOAPString"]],
        ["in", "address_id", ["::SOAP::SOAPInt"]],
        ["retval", "return", ["::SOAP::SOAPInt"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ]
  ]

  def initialize(endpoint_url = nil)
    endpoint_url ||= DefaultEndpointUrl
    super(endpoint_url, nil)
    self.mapping_registry = DefaultMappingRegistry::EncodedRegistry
    self.literal_mapping_registry = DefaultMappingRegistry::LiteralRegistry
    init_methods
  end

private

  def init_methods
    Methods.each do |definitions|
      opt = definitions.last
      if opt[:request_style] == :document
        add_document_operation(*definitions)
      else
        add_rpc_operation(*definitions)
        qname = definitions[0]
        name = definitions[2]
        if qname.name != name and qname.name.capitalize == name.capitalize
          ::SOAP::Mapping.define_singleton_method(self, qname.name) do |*arg|
            __send__(name, *arg)
          end
        end
      end
    end
  end
end


end
